[theme]
primaryColor = "#000000ff"          # Buttons, accents
backgroundColor = "#ff914d4f"       # MAIN background
secondaryBackgroundColor = "#ff313154"   # SIDEBAR background
textColor = "#FFFFFF"             # You need light text for dark backgrounds
